version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: fast-delivery-db
    ports:
      - "27017:27017"

  backend:
    build: ./back
    container_name: fast-delivery-backend
    ports:
      - "3001:3001"
    volumes:
      # enlazar mi carpeta al workdir
      - ./back:/back
    depends_on:
      - mongodb

  frontend:
    build: ./front
    container_name: fast-delivery-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
