version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: fast-delivery-db
    ports:
      - '27017:27017'

  backend:
    build: .
    container_name: fast-delivery-backend
    ports:
      - '8080:8080'
    environment:
      - URL="mongodb://mongodb/fast-delivery-back"
    depends_on:
      - mongodb
    volumes:
      - .:/back
